click("MozillaFirefox.png")
wait("url_bar.png", 10)
type("url_bar.png", "qtaste \n")
waitVanish("search_field.png")
wait("qtaste_link.png")
click("qtaste_link.png")
wait("qtaste_logo.png")
click("close_tab.png")
waitVanish("qtaste_logo.png")
