
AppName = "Qtaste"
GitHubRepositoryUrl = "qspin/qtaste"
ReleaseNotesTemplate = "./qtaste_release_notes_template.xml"
ReleaseNotesOutputFile = "../qtaste_release_notes.xml"

# Version Info (generated by maven)
VersionFile = "../../../../Version.txt"
VersionTag = "qtaste-version"

